version: '3.8'
services:
  auth-user-service:
    build: ../backend/auth-user-service
    env_file:
      - ../.env.example
    ports:
      - "4001:4001"
    depends_on:
      - mongo
  agency-fleet-service:
    build: ../backend/agency-fleet-service
    env_file:
      - ../.env.example
    ports:
      - "4002:4002"
    depends_on:
      - mongo
  search-availability-service:
    build: ../backend/search-availability-service
    env_file:
      - ../.env.example
    ports:
      - "4003:4003"
    depends_on:
      - mongo
      - redis
      - elasticsearch
  reservation-service:
    build: ../backend/reservation-service
    env_file:
      - ../.env.example
    ports:
      - "4004:4004"
    depends_on:
      - mongo
  payment-billing-service:
    build: ../backend/payment-billing-service
    env_file:
      - ../.env.example
    ports:
      - "4005:4005"
    depends_on:
      - mongo
  review-support-service:
    build: ../backend/review-support-service
    env_file:
      - ../.env.example
    ports:
      - "4006:4006"
    depends_on:
      - mongo
  frontend:
    build: ../frontend
    ports:
      - "3000:3000"
  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
volumes:
  mongo_data:
  esdata:
